// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDitvC1NgZf3lVNUycRF3ZgZeyGUuL3_dk',
    appId: '1:525047488380:web:319805d5bcfcd24b40cef9',
    messagingSenderId: '525047488380',
    projectId: 'enruta-app-74653',
    authDomain: 'enruta-app-74653.firebaseapp.com',
    databaseURL: 'https://enruta-app-74653-default-rtdb.firebaseio.com',
    storageBucket: 'enruta-app-74653.firebasestorage.app',
    measurementId: 'G-NF5PV411LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdCQ7wCECV9AxshDBnqPdnjCownXoDyWQ',
    appId: '1:525047488380:android:de7b4dff12b4e0ab40cef9',
    messagingSenderId: '525047488380',
    projectId: 'enruta-app-74653',
    databaseURL: 'https://enruta-app-74653-default-rtdb.firebaseio.com',
    storageBucket: 'enruta-app-74653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSNeecc6wvNyw12YVagj0cf8HODyY1l_w',
    appId: '1:525047488380:ios:aae509e622f066d040cef9',
    messagingSenderId: '525047488380',
    projectId: 'enruta-app-74653',
    databaseURL: 'https://enruta-app-74653-default-rtdb.firebaseio.com',
    storageBucket: 'enruta-app-74653.firebasestorage.app',
    iosBundleId: 'com.example.enrutaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSNeecc6wvNyw12YVagj0cf8HODyY1l_w',
    appId: '1:525047488380:ios:aae509e622f066d040cef9',
    messagingSenderId: '525047488380',
    projectId: 'enruta-app-74653',
    databaseURL: 'https://enruta-app-74653-default-rtdb.firebaseio.com',
    storageBucket: 'enruta-app-74653.firebasestorage.app',
    iosBundleId: 'com.example.enrutaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDitvC1NgZf3lVNUycRF3ZgZeyGUuL3_dk',
    appId: '1:525047488380:web:989a2a33ee09ce9540cef9',
    messagingSenderId: '525047488380',
    projectId: 'enruta-app-74653',
    authDomain: 'enruta-app-74653.firebaseapp.com',
    databaseURL: 'https://enruta-app-74653-default-rtdb.firebaseio.com',
    storageBucket: 'enruta-app-74653.firebasestorage.app',
    measurementId: 'G-NT9KKHLT8R',
  );
}
